### ISSUE TITLE
provide master-data and introduce schema-versioning

### ISSUE THREAD

**Issue by hohwille** [devonfw-sample/devon4quarkus-reference#10]
When #9 is implemented, we should do the following:

* search the web for some kind of free open-data sample product catalog (e.g. as CSV file that we can copy & modify without violating licenses). If we cannot find something we can make up our own product master-data.
* create SQL script for DDL (create table statements for data model)
* create SQL script that inserts this data
* integrate flyway to run these SQLs: https://quarkus.io/guides/flyway

Acceptance criteria:
When I clone, build and start the app, I can read the product list via REST service and get a larger list of products (100+) and that list looks reasonable (products and prices make kind of sense).

**Comment by GuentherJulian** [comment]
@lilliCao Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/quarkus-60db0e4882f8700010cdc598/issues/devonfw-sample/devon4quarkus-reference/10?planning-poker)
