### ISSUE TITLE
Create second quarkus sample app

### ISSUE THREAD

**Issue by hohwille** [devonfw-sample/devon4quarkus-reference#11]
With #8 , #9 and #10 we want to improve our first sample app for quarkus.
When this is done, we want to create a second app with this story:
The idea is to create a second app:
* repository: [devon4quarkus-order](https://github.com/devonfw-sample/devon4quarkus-order/)
* component name `ordermanagement`
* entities `Item` and `Order` - general idea from [here](https://github.com/devonfw-training/java-foundations/blob/master/documentation/2-dataaccess.asciidoc#create-entities), however using `MonetaryAmount` for price (see #9). Why are attributes like price stored redundantly? The price in the master-data (productmanagement) may change but that shall not change the history of existing Orders that have already been paid. Same for `title` (called `name` in the linked UML diagram). Do not copy details such as `description` from product. Also add `productId` as property to `Item`. As this is pointing to an entity from a different service/app, it can not be a foreign key constraint but is just a long number.

In order to create an `Item` for a given product-ID this app shall use [quarkus rest-client](https://quarkus.io/guides/rest-client) to get the product data and fill according properties in the item. Things like `creationDate` shall be auto-populated by use-case (`Instant.now()`).

As discussed in #6 we should also demonstrate a REST service that gets generated from an OpenAPI contract. We could generate the OpenAPI contract for our product service (see https://github.com/devonfw/devon4j/issues/216). Then we could include this OpenAPI file here and generate the REST API code artefacts for the quarkus-rest-client from it automatically.

**Comment by GuentherJulian** [comment]
@lilliCao Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/quarkus-60db0e4882f8700010cdc598/issues/devonfw-sample/devon4quarkus-reference/11?planning-poker)

**Comment by Przemek-Majtyka** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/quarkus-60db0e4882f8700010cdc598/issues/devonfw-sample/devon4quarkus-reference/11?planning-poker) with ZenHub @TugbaDalmaz
