### ISSUE TITLE
Fix test cases and create workflow for checking the tests

### ISSUE THREAD

**Issue by GuentherJulian** [devonfw-sample/devon4quarkus-reference#18]
In the pull request https://github.com/devonfw-sample/devon4quarkus-reference/pull/15#issuecomment-920909593 it was found that the test cases fail after changing the entity "Animal" to "Product". Probably that is why the test data in the xls files do not match anymore. This should be fixed. We should also add a workflow for testing the test cases, so that we see such errors directly in the pull request in the future.

**Comment by sobkowiak** [comment]
Tests should be run in the CI/CD workflow. Actually only `mvn compile` is used to build the source code

**Comment by GuentherJulian** [comment]
Closed with https://github.com/devonfw-sample/devon4quarkus-reference/pull/20
