### ISSUE TITLE
Remove @APIResponse annotations and add ServicedocGen plugin to support OpenAPI generation

### ISSUE THREAD

**Issue by GuentherJulian** [devonfw-sample/devon4quarkus-reference#26]
The annotations in the REST service (`@APIResponse`) should be removed as it adds redundancy and is an anti-pattern (see comment https://github.com/devonfw-sample/devon4quarkus-reference/pull/24#discussion_r728737559). Instead we can add the [ServicedocGen maven plugin](https://github.com/mojohaus/servicedocgen-maven-plugin), which was improved and also supports OpenAPI definition generation and SwaggerUI now.

**Comment by isandesh1986** [comment]
Just FYI. Please refer https://github.com/devonfw-sample/devon4quarkus-reference/pull/29
This has been implemented and merged.
