### ISSUE TITLE
Satisfy devonfw coding conventions

### ISSUE THREAD

**Issue by hohwille** [devonfw-sample/devon4quarkus-reference#4]
With devon4quarkus we want to keep our coding conventions that we already have in devon4j.
https://github.com/devonfw/devon4j/blob/master/documentation/coding-conventions.asciidoc

The latest docs about this aligned with spring and quarkus can be found here and will be merged soon:
https://github.com/hohwille/devon4j/blob/feature/420-d4q-coding/documentation/coding-conventions.asciidoc#stateless-programming

The following required changes are what I can easily see:

* Use `Dto` instead of `DTO` as Suffix
* Use code-formatter and reformat the code. Most code seems to match but in some places I can see a mixture of indendation with 2 or 4 spaces, maybe even tabs. For Eclipse we preconfigure formatter and save-actions so nothing can ever get wrong in Java code. Are you using devonfw-ide with Eclipse for coding or are you using IntelliJ? In case you are an IntelliJ user, your contribution to improve this in devonfw-ide would be very welcome: Can we deliver IntelliJ formatter config in our settings GIT repo like we do for eclipse? Can we somehow assure that these formatter config is automatically setup and configured for IntelliJ by devonfw-ide? Can we even pre-configure something like SaveActions in Eclipse that automatically format the code whenever you save a file? Or does IntelliJ follow a different philosophy to archive clean and consistently formatted code in projects? AFAIK the commit dialog in IntelliJ support formatting of all the new code...

**Comment by GuentherJulian** [comment]
> Are you using devonfw-ide with Eclipse for coding or are you using IntelliJ?

I had used another version of Eclipse where no save action was configured. Now I just used Eclipse from devonfw and saved the files again
