### ISSUE TITLE
Problem with 'docker-compose up'

### ISSUE THREAD

**Issue by pschreie** [devonfw-sample/devon4quarkus-reference#40]
Hi all, 
I am currently trying to run a test application in my local Kubernetes cluster with Devon4Quarkus-Reference (https://github.com/devonfw-sample/devon4quarkus-reference). Unfortunately, I get some error messages already with the command 'docker-compose up', which I can't explain even after research.

![484af3d2-60c2-48b7-93f4-e5aa5c0bedab](https://user-images.githubusercontent.com/100365277/155569618-611179ff-de09-4efc-bb70-4a0a92e9c84c.jpg)

The first error, that PostgreSql could not start, was solved by deleting line 12 in docker-compose.yaml. 

> `command: [-cmax_prepared_transactions=100]`

The other error is with Matric. See screenshots:

![6b5e8509-455d-4286-b84d-73f36d17b960](https://user-images.githubusercontent.com/100365277/155570153-2e1e352a-9de2-4e8a-8abb-536770442938.jpg)

![dbf65d42-f10f-49bf-82de-2074dbe9a189](https://user-images.githubusercontent.com/100365277/155570161-23d200ec-b96c-464e-914f-2f635f43dcb1.jpg)

Is there also a solution for this as with the database?

Thanks a lot.
Patrick

**Comment by sundharakanth** [comment]
Hi Patrick,
     We discussed in Teams Channel and other than the known issues (Monitoring/Logging), you are able to check the application running after deployment. Please confirm.
Thanks,
Sundhar

**Comment by pschreie** [comment]
Hi Sundhar, 

i can run the Application on my local machine, but now  i try it to run on a local kubernetes/minicube cluster for test reasons and this is not working yet. I am working on. 
Thanks
Patrick

**Comment by GuentherJulian** [comment]
For Kubernetes deployment use the files from the `k8s` folder and for the OpenTelemetry components have a look at the [documentation](https://github.com/devonfw-sample/devon4quarkus-reference/blob/master/documentation/opentelemetry-deployment.asciidoc). The docker file can not be used just like this I think. The application and the database should work, but the configuration for the other components needs to be adjusted.

**Comment by pschreie** [comment]
Hi Julian, 

now it's working :)

Thanks
Patrick
