### ISSUE TITLE
Change quarkus reference app from animals to products

### ISSUE THREAD

**Issue by hohwille** [devonfw-sample/devon4quarkus-reference#9]
As discussed in #8 we need to think further and create a design for our sample apps.
Changing things now is still easy and has low effort.

So technically with this story we want to refactor the sample app in this repo such that it provides a service for products (master-data). This means:
* Rename the packaging from `com.devonfw.demoquarkus` to `com.devonfw.quarkus.productmanagement`
* Change `Animal` to `Product`
* Product should have these properties (in addition to `id` and "version"):
   * title (String)
   * price ([MonetaryAmount](https://javamoney.github.io/apidocs/javax/money/MonetaryAmount.html)) - then we can also demonstrate [AttributeConverter](https://github.com/devonfw/devon4j/blob/master/documentation/guide-jpa.asciidoc#entities-and-datatypes) and [Json(De)Serializer](https://github.com/devonfw/devon4j/blob/master/documentation/guide-json.asciidoc#custom-mapping). For the record: We do not need to support multiple currencies - can be fixed to a single-one like EURO. Transformation between currencies is complex and more or less only works properly via externally provided services. Therefore we could omit the currency in DB and only store the value. For storing the precision is not so important so two digits are sufficient for a real-world example. However, computations like tax rates have to work with precision that is guaranteed by MonetaryAmount or BigDecimal and would lead to invalid results when using `double` or `float`.
   * description (String)
   * optionally more to add later outside this story (e.g. picture as URL or [BLOB](https://github.com/devonfw/devon4j/blob/master/documentation/guide-blob-support.asciidoc))

**Comment by hohwille** [comment]
Hint: When it comes to search-criteria it makes sense to consider flexibility:
* An attribute like price will be searched as a range so in searchCriteria for product I would expect `priceMin` and `priceMax` attributes. If both are equal to `X` you want to search `price = X` otherwise `price >= :priceMin` and `price <= :priceMax` while omitting these WHERE conditions if min or max is null.
* An attribute like `title` could match using equal, contains or like. In devon4j we had some framework code for such criterias: [LikePatternSyntax](https://github.com/devonfw/devon4j/blob/466368dbeb229a27f53c1f3ad1dd93fd2f5df418/modules/basic/src/main/java/com/devonfw/module/basic/common/api/query/LikePatternSyntax.java), [StringSearchOperator](https://github.com/devonfw/devon4j/blob/466368dbeb229a27f53c1f3ad1dd93fd2f5df418/modules/basic/src/main/java/com/devonfw/module/basic/common/api/query/StringSearchOperator.java), [StringSearchConfigTo](https://github.com/devonfw/devon4j/blob/466368dbeb229a27f53c1f3ad1dd93fd2f5df418/modules/basic/src/main/java/com/devonfw/module/basic/common/api/query/StringSearchConfigTo.java), [QueryHelper](https://github.com/devonfw/devon4j/blob/466368dbeb229a27f53c1f3ad1dd93fd2f5df418/modules/jpa-basic/src/main/java/com/devonfw/module/jpa/dataaccess/api/QueryHelper.java#L171), etc. - please start simple but already see that it will get more complex so design wisely :)

**Comment by GuentherJulian** [comment]
@lilliCao Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/quarkus-60db0e4882f8700010cdc598/issues/devonfw-sample/devon4quarkus-reference/9?planning-poker)

**Comment by TugbaDalmaz** [comment]
Included in task #9 (Change quarkus reference app from animals to products)
